export const AUTH = 'AUTH'
export const CATEGORY = 'CATEGORY'
export const BOOK = 'BOOK'
export const USER = 'USER'
export const BORROWER = 'BORROWER'
export const ACCOUNT = 'ACCOUNT'
export const ROLES = 'ROLES'
